// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Todo.Data;

#nullable disable

namespace Todo.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240509161754_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Todo.Entities.TodoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "პირველი საქმის აღწერა...",
                            EndDate = new DateTime(2024, 5, 9, 21, 17, 53, 807, DateTimeKind.Local).AddTicks(2654),
                            Priority = 2,
                            StartDate = new DateTime(2024, 5, 9, 20, 17, 53, 807, DateTimeKind.Local).AddTicks(2653),
                            Status = 1,
                            Title = "პირველი საქმე"
                        },
                        new
                        {
                            Id = 2,
                            Description = "მეორე საქმის აღწერა...",
                            EndDate = new DateTime(2024, 5, 9, 21, 17, 53, 807, DateTimeKind.Local).AddTicks(2660),
                            Priority = 1,
                            StartDate = new DateTime(2024, 5, 9, 20, 17, 53, 807, DateTimeKind.Local).AddTicks(2659),
                            Status = 1,
                            Title = "მეორე საქმე"
                        },
                        new
                        {
                            Id = 3,
                            Description = "მესამე საქმის აღწერა...",
                            EndDate = new DateTime(2024, 5, 10, 1, 17, 53, 807, DateTimeKind.Local).AddTicks(2662),
                            Priority = 4,
                            StartDate = new DateTime(2024, 5, 9, 20, 17, 53, 807, DateTimeKind.Local).AddTicks(2661),
                            Status = 2,
                            Title = "მესამე საქმე"
                        },
                        new
                        {
                            Id = 4,
                            Description = "მეოთხე საქმის აღწერა...",
                            EndDate = new DateTime(2024, 5, 16, 20, 17, 53, 807, DateTimeKind.Local).AddTicks(2664),
                            Priority = 1,
                            StartDate = new DateTime(2024, 5, 9, 20, 17, 53, 807, DateTimeKind.Local).AddTicks(2663),
                            Status = 1,
                            Title = "მეოთხე საქმე"
                        },
                        new
                        {
                            Id = 5,
                            Description = "მეხუთე საქმის აღწერა...",
                            EndDate = new DateTime(2024, 5, 12, 20, 17, 53, 807, DateTimeKind.Local).AddTicks(2668),
                            Priority = 3,
                            StartDate = new DateTime(2024, 5, 9, 20, 17, 53, 807, DateTimeKind.Local).AddTicks(2667),
                            Status = 1,
                            Title = "მეხუთე საქმე"
                        },
                        new
                        {
                            Id = 6,
                            Description = "მეექვსე საქმის აღწერა...",
                            EndDate = new DateTime(2024, 5, 19, 20, 17, 53, 807, DateTimeKind.Local).AddTicks(2670),
                            Priority = 2,
                            StartDate = new DateTime(2024, 5, 9, 20, 17, 53, 807, DateTimeKind.Local).AddTicks(2669),
                            Status = 2,
                            Title = "მეექვსე საქმე"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
